# Generated by Django 3.2 on 2021-04-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('faculty_choice', models.CharField(choices=[('Лечебный', 'Лечебный'), ('Медико-профилактический', 'Медико-профилактический'), ('Педиатрический', 'Педиатрический'), ('Стоматологический', 'Стоматологический'), ('Военно-медицинский', 'Военно-медицинский'), ('Иностранных учащихся', 'Иностранных учащихся'), ('Фармацевтический', 'Фармацевтический'), ('Профориентации и довузовской подготовки', 'Профориентации и довузовской подготовки'), ('Факультет повышения квалификации и переподготовки кадров', 'Факультет повышения квалификации и переподготовки кадров')], max_length=75, verbose_name='Факультет')),
                ('course_choice', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='SemesterOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_start', models.DateField(verbose_name='Начало семестра')),
                ('server_week_type_choice', models.CharField(choices=[('1', 'Нечетная'), ('2', 'Четная')], default='1', help_text='Тип недели обязательное значение', max_length=1, verbose_name='Тип первой учебной недели')),
                ('semester_end', models.DateField(verbose_name='Конец семестра')),
            ],
            options={
                'verbose_name': 'Настройки семестра',
                'verbose_name_plural': 'Настройки семестра',
            },
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day_choice', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресение', 'Воскресение')], max_length=100, verbose_name='День недели')),
                ('subject', models.CharField(max_length=100, verbose_name='Дисциплина')),
                ('lesson_type_choice', models.CharField(choices=[('ЛК', 'Лекция'), ('ПЗ', 'Практическое'), (' ', 'Не указывать')], max_length=100, verbose_name='Тип занятия')),
                ('week_type_choice', models.CharField(choices=[('0', 'Каждая'), ('1', 'Нечетная'), ('2', 'Четная'), ('-1', 'Иначе')], max_length=100, verbose_name='Тип недели')),
                ('special_days', models.CharField(blank=True, max_length=100, verbose_name='Отдельные дни')),
                ('auditory', models.CharField(blank=True, max_length=10, verbose_name='Аудитория')),
                ('start_lesson_time', models.TimeField(verbose_name='Время начала пары')),
                ('end_lesson_time', models.TimeField(verbose_name='Время конца пары')),
                ('employee_full_name', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель (ФИО полностью)')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('group_id_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.group')),
            ],
            options={
                'verbose_name': 'Пары',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
