# Generated by Django 3.2 on 2021-05-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupNumber', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('facultyChoice', models.CharField(choices=[('Лечебный', 'Лечебный'), ('Медико-профилактический', 'Медико-профилактический'), ('Педиатрический', 'Педиатрический'), ('Стоматологический', 'Стоматологический'), ('Военно-медицинский', 'Военно-медицинский'), ('Иностранных учащихся', 'Иностранных учащихся'), ('Фармацевтический', 'Фармацевтический'), ('Профориентации и довузовской подготовки', 'Профориентации и довузовской подготовки'), ('Факультет повышения квалификации и переподготовки кадров', 'Факультет повышения квалификации и переподготовки кадров')], max_length=75, verbose_name='Факультет')),
                ('courseChoice', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='Курс')),
                ('semesterStartDate', models.DateField(verbose_name='Начало семестра')),
                ('semesterEndDate', models.DateField(verbose_name='Конец семестра')),
                ('groupWeekTypeChoice', models.CharField(choices=[('1', 'Нечетная'), ('2', 'Четная'), (None, 'Не учитывать')], default=None, max_length=1, verbose_name='Тип первой учебной недели')),
                ('sessionStartDate', models.DateField(verbose_name='Начало экзаменов')),
                ('sessionEndDate', models.DateField(verbose_name='Конец экзаменов')),
                ('educationalPracticeStartDate', models.DateField(verbose_name='Начало учебной практики')),
                ('educationalPracticeEndDate', models.DateField(verbose_name='Конец учебной практики')),
                ('holidaysStartDate', models.DateField(verbose_name='Начало каникул')),
                ('holidaysEndDate', models.DateField(verbose_name='Конец каникул')),
            ],
            options={
                'verbose_name': 'информацию группы',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDayChoices', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресение', 'Воскресение')], max_length=100, verbose_name='День недели')),
                ('subject', models.CharField(max_length=100, verbose_name='Дисциплина')),
                ('lessonTypeChoice', models.CharField(choices=[('ЛК', 'Лекция'), ('ПЗ', 'Практическое'), (' ', 'Не указывать')], max_length=100, verbose_name='Тип занятия')),
                ('weekTypeChoice', models.CharField(choices=[('0', 'Каждая'), ('1', 'Нечетная'), ('2', 'Четная'), ('-1', 'Иная')], max_length=100, verbose_name='Тип недели')),
                ('specialDays', models.CharField(blank=True, help_text='Если занятие проводится по отдельным датам. Например, <b>18.09 15.10 16.11</b>', max_length=100, verbose_name='Отдельные дни')),
                ('auditory', models.CharField(blank=True, max_length=10, verbose_name='Аудитория')),
                ('startLessonTime', models.TimeField(verbose_name='Время начала пары')),
                ('endLessonTime', models.TimeField(verbose_name='Время конца пары')),
                ('employeeFullName', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель (ФИО полностью)')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('groupIdConnector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.group')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
