# Generated by Django 3.2 on 2021-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_week_type_needed',
            field=models.BooleanField(default=1, verbose_name='Учитывается ли четность недели?'),
            preserve_default=False,
        ),
    ]
