# Generated by Django 3.2 on 2021-04-29 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_group_is_week_type_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='semester_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Конец семестра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='semester_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало семестра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='session_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Конец экзаменов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='session_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало экзаменов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='week_type_choice',
            field=models.CharField(choices=[('0', 'Каждая'), ('1', 'Нечетная'), ('2', 'Четная'), ('-1', 'Иная')], max_length=100, verbose_name='Тип недели'),
        ),
        migrations.AlterField(
            model_name='semesteroptions',
            name='server_week_type_choice',
            field=models.CharField(choices=[('1', 'Нечетная'), ('2', 'Четная')], default='1', help_text='Тип недели обязательное значение', max_length=1, verbose_name='Тип текущей учебной недели'),
        ),
    ]
