# Generated by Django 3.2 on 2021-04-29 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210429_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'информацию группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='grouplesson',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_week_type_needed',
        ),
        migrations.AddField(
            model_name='group',
            name='educational_practice_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Конец учебной практики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='educational_practice_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Начало учебной практики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_week_type_choice',
            field=models.CharField(choices=[('1', 'Нечетная'), ('2', 'Четная'), (None, 'Не учитывать')], default=None, max_length=1, verbose_name='Тип первой учебной недели'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='special_days',
            field=models.CharField(blank=True, help_text='Если занятие проводится по отдельным датам. Например, <b>18.09 15.10 16.11</b>', max_length=100, verbose_name='Отдельные дни'),
        ),
    ]
