# Generated by Django 3.2 on 2021-04-29 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210429_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='holidays_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Конец каникул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='holidays_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало каникул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='educational_practice_end_date',
            field=models.DateField(verbose_name='Конец учебной практики'),
        ),
        migrations.AlterField(
            model_name='group',
            name='educational_practice_start_date',
            field=models.DateField(verbose_name='Начало учебной практики'),
        ),
    ]
